from .agent_routing import (
    DEFAULT_SKILLS,
    LEGACY_SKILLS,
    RoutingDecision,
    RoutingStatus,
    ScientificIntentRequest,
    discoverable_skill_names,
    extract_scientific_capability,
    is_default_skill,
    route_scientific_intent,
)
from .artifacts import (
    BundleVerificationResult,
    DownstreamSuggestion,
    FigureArtifact,
    InputArtifact,
    OutputArtifact,
    RunBundle,
    load_run_bundle,
    verify_run_bundle,
)
from .backends import BackendUnavailable, is_available, probe, probe_all, require
from .capabilities import (
    CANONICAL_CAPABILITIES,
    BackendRequirement,
    CapabilityContract,
    CapabilityEvaluationResult,
    EvidenceRequirement,
    InputSpecification,
    Precondition,
    RefusalTrigger,
    SemanticInputType,
    evaluate_capability_preconditions,
    find_capabilities_by_intent,
    get_capability,
    list_capabilities,
)
from .claim_checker import (
    ClaimAuditResult,
    ClaimViolation,
    ClaimViolationType,
    audit_prohibited_claims,
)
from .contracts import (
    ABSTAIN,
    GRADE_A,
    GRADE_B,
    GRADE_C,
    RESEARCH_USE_ONLY,
    ConclusionMaturity,
    ConclusionStatus,
    DimensionGrade,
    EvidenceCard,
    EvidenceGrade,
    ExecutionState,
    attach_meta,
    refuse,
    synthesize_conclusion_maturity,
    synthesize_conclusion_status,
)
from .doctor import run_doctor
from .gate import DoctorGateError, require_doctor, write_doctor_report
from .integrity import (
    audit_expression_matrix,
    audit_parameter_stability,
    audit_spatial_coordinates,
    audit_statistical_significance,
)
from .inventory import (
    SKILLS,
    active_skills,
    as_markdown_table,
    canonical_skills,
    core_skills,
    get_skill,
    skills_by_status,
    skills_by_tier,
)
from .pipeline_config import load_pipeline_config, merge_config
from .provenance import capture_environment, sha256_file, sidecar
from .versions import PINS, PITFALLS, PLUGIN_VERSION

__version__ = PLUGIN_VERSION

__all__ = [
    "ABSTAIN",
    "BundleVerificationResult",
    "CANONICAL_CAPABILITIES",
    "DownstreamSuggestion",
    "FigureArtifact",
    "GRADE_A",
    "GRADE_B",
    "GRADE_C",
    "InputArtifact",
    "OutputArtifact",
    "RESEARCH_USE_ONLY",
    "RunBundle",
    "BackendRequirement",
    "BackendUnavailable",
    "CapabilityContract",
    "CapabilityEvaluationResult",
    "ConclusionMaturity",
    "ConclusionStatus",
    "DEFAULT_SKILLS",
    "DimensionGrade",
    "DoctorGateError",
    "EvidenceCard",
    "EvidenceGrade",
    "EvidenceRequirement",
    "ExecutionState",
    "InputSpecification",
    "LEGACY_SKILLS",
    "PINS",
    "PITFALLS",
    "Precondition",
    "RefusalTrigger",
    "SKILLS",
    "SemanticInputType",
    "__version__",
    "active_skills",
    "as_markdown_table",
    "attach_meta",
    "audit_expression_matrix",
    "audit_parameter_stability",
    "audit_prohibited_claims",
    "audit_spatial_coordinates",
    "audit_statistical_significance",
    "canonical_skills",
    "ClaimAuditResult",
    "ClaimViolation",
    "ClaimViolationType",
    "core_skills",
    "discoverable_skill_names",
    "evaluate_capability_preconditions",
    "extract_scientific_capability",
    "find_capabilities_by_intent",
    "get_capability",
    "get_skill",
    "is_available",
    "is_default_skill",
    "list_capabilities",
    "load_pipeline_config",
    "load_run_bundle",
    "merge_config",
    "probe",
    "probe_all",
    "refuse",
    "require",
    "require_doctor",
    "route_scientific_intent",
    "RoutingDecision",
    "RoutingStatus",
    "ScientificIntentRequest",
    "run_doctor",
    "sha256_file",
    "sidecar",
    "skills_by_status",
    "skills_by_tier",
    "synthesize_conclusion_maturity",
    "synthesize_conclusion_status",
    "verify_run_bundle",
    "write_doctor_report",
    "capture_environment",
]
