// ---------------------------------------------------------------------------
// SpatialWarrant — project blueprint content
// 「证据可审计的乳腺癌肿瘤–免疫边界空间图谱」
// All datasets are public; no wet lab; designed for a 32 GB RAM laptop (CPU only).
// ---------------------------------------------------------------------------

export const PROJECT = {
  name: "SpatialWarrant",
  tagline:
    "An evidence-audited spatial atlas of the tumor–immune boundary in human breast cancer",
  taglineZh: "证据可审计的乳腺癌肿瘤–免疫边界空间图谱（Visium × scRNA-seq）",
  question:
    "主问题：在 6 个公开乳腺癌 Visium 样本中，仅由发布者病理区域和空间几何预定义的肿瘤–基质边界，是否显示跨样本方向一致的预指定免疫/IFN 程序差异？扩展问题保留：scRNA 参考映射、niche、配体–受体、外部切片迁移与证据边界。",
  pitch:
    "别人展示「AI 跑通了一条 pipeline」；我们展示一次真实、允许失败的空间分析，并精确说明哪些结论不能下。每个发现都绑定输入、方法、结果、限制和 EvidenceCard；阳性、阴性与不确定结果均可成为作品的一部分。",
  whyItWins: [
    {
      title: "叙事差异化：Honesty as a feature",
      body: "评委大概率会看到几十个漂亮 UMAP。一个能自动给结论「封顶」并拒绝临床过度解读的空间图谱，天然更让 Life Sciences 团队眼前一亮。",
    },
    {
      title: "三件套闭环：Rosalind 规划 → 插件执行 → BioNexus 审计",
      body: "NGS Analysis Workbench 负责数据理解与 plan-first 设计；Life Sciences Literature 负责文献核对；本地 Python 执行自定义统计；BioNexus 负责 warrant、EvidenceCard、Ledger 与 Evidence Debt。",
    },
    {
      title: "有发布者提供的病理学正交参考",
      body: "Wu et al. 2021 的 6 张 Visium 切片带有病理区域标注，可用于定义几何边界和一致性检查；它来自同一研究，不能称为独立真值或外部复现。",
    },
    {
      title: "配对设计 + 多患者 → 有真正的统计故事",
      body: "边界 vs 核心在同一样本内配对。先核实 patient–sample–section 关系；只有 6 张切片确属 6 个独立患者时，才能写跨 6 名患者 pseudobulk。",
    },
    {
      title: "内置一个「陷阱」演示",
      body: "故意让 agent 从单张切片下人群级/因果级结论，展示 BioNexus 当场封顶/拒绝的截图。这是最容易被转发的画面。",
    },
    {
      title: "笔记本可复现",
      body: "按 CPU 和 32 GB RAM 设计，逐样本执行并保留环境、哈希、命令和日志。峰值内存与耗时在完成真实运行后再填写。",
    },
  ],
  memoryBudget: [
    { item: "scRNA 参考（GSE176078，分层下采样至 40k 细胞，稀疏矩阵）", gb: 2.5 },
    { item: "HVG 2000 × 40k 稠密矩阵 + PCA / 邻接图", gb: 1.5 },
    { item: "6 张 Visium 切片（~2–5k spots/张）+ 高清 H&E", gb: 1.0 },
    { item: "Tangram cluster-mode 映射（映射 cluster 而非单细胞）", gb: 2.0 },
    { item: "squidpy 邻域富集 / 共现 / Moran's I", gb: 1.0 },
    { item: "pydeseq2 pseudobulk + LIANA 配体–受体", gb: 1.0 },
    { item: "BioNexus 审计 / ledger / debt DAG + 系统余量", gb: 3.0 },
  ],
  hardware:
    "32 GB RAM 笔记本，CPU-only。表中数值是设计预算，不是实测峰值；Tangram、ingest 和 marker/NNLS 各自承担不同的敏感性角色。",
};

export const PLUGINS = [
  {
    plugin: "NGS Analysis Workbench 0.2.16",
    vendor: "OpenAI (ChatGPT / Codex)",
    role: "数据理解、plan-first 设计与实时工作流能力核查；兼容工作流存在且真实运行时才计为执行",
    howUsed: [
      "让 Workbench 先识别处理后矩阵、实验单位、配对关系与不能支持的结论",
      "查询实时目录是否存在 processed Visium/scRNA 矩阵入口；不把本地 Python 冒充注册工作流",
      "若调用 Slide Viewer，单独记录其真实插件名称和返回",
      "把可复用步骤沉淀为 Skill（如 subsample-by-patient）",
    ],
    proofArtifact: "截图：Workbench 计划、NGS Analysis Workbench 真实调用与目录/能力返回",
    accent: "sky",
  },
  {
    plugin: "Life Sciences Literature 0.1.5",
    vendor: "OpenAI (Codex)",
    role: "原论文与方法文献核对、结果背景解释；Astra/Sol 是模型选择，不是插件名称",
    howUsed: [
      "检索 Wu et al. 2021 Nat Genet 与后续 TME 边界文献，提炼可检验假设",
      "为边界富集的配体–受体轴（如 CXCL9/10–CXCR3、CD274–PDCD1、TGFB1）拉取 Open Targets / 文献支持",
      "生成 Methods 段落与图注初稿，交给 BioNexus external-evidence-audit 复核",
      "对比自身结论与文献时，让它明确标注「一致 / 矛盾 / 无报道」",
    ],
    proofArtifact: "截图：插件返回的带引用的文献综合；与 BioNexus 审计结果并排",
    accent: "violet",
  },
  {
    plugin: "BioNexus Reliability 1.0.0-rc.4",
    vendor: "你自己的开源插件 · Apache 2.0",
    role: "科学可靠性层：warrant 判定、EvidenceCard、Claim–Evidence Ledger、Evidence Debt",
    howUsed: [
      "bionexus preflight：在跑之前评估设计可识别性（配对 / 患者数 / 批次）",
      "旗舰能力 scrna.annotation_evidence：给每个 cluster 标签打证据分",
      "旗舰能力 scrna.pseudobulk_de：边界 vs 核心 DE，自动封顶 claim class",
      "空间技能：坐标/邻接/Moran/基础图；自定义病理边界与 pseudobulk 代码另行记录",
      "MCP 工具 search_geo / search_reactome / search_string / search_uniprot 做数据与通路查询",
      "bionexus ledger + debt audit/payoff/graph：输出 PROV-O 账本与 Evidence Debt DAG",
      "BioFailureBench 风格陷阱：故意提交过度解读，截图它被 capped/REFUSED",
    ],
    proofArtifact: "截图：EvidenceCard（ceiling=FRAGILE 且 claim 被封顶）、Evidence Debt Mermaid DAG、陷阱被拒绝",
    accent: "emerald",
  },
];

export const DATASETS = [
  {
    name: "Wu et al. 2021 乳腺癌单细胞图谱",
    accession: "GEO GSE176078",
    sourceUrl: "https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE176078",
    modality: "scRNA-seq (10x 3')",
    role: "去卷积与细胞来源解释参考；作者标签是 producer annotation，不是独立真值",
    sizeNote: "GEO 补充归档约 533 MB；解压大小与细胞数在下载后核实，再决定是否分层下采样至 40k",
    ramNote: "≈ 2.5 GB 加载；下采样后 < 1 GB",
    priority: "primary",
  },
  {
    name: "Wu et al. 2021 Visium 切片（含病理标注）",
    accession: "Zenodo 4739739",
    sourceUrl: "https://zenodo.org/records/4739739",
    modality: "10x Visium + H&E + pathologist annotation",
    role: "6 张切片（CID4290 / CID4465 / CID44971 / CID4535 / 1142243F / 1160920F）；亚型和患者对应关系先从元数据核实；病理标注是同研究的正交参考",
    sizeNote: "Zenodo 页面全部压缩文件约 921 MB；各文件大小与哈希在输入清单固化",
    ramNote: "≈ 1 GB（含高清图）",
    priority: "primary",
  },
  {
    name: "10x Genomics 公开 Visium：Human Breast Cancer, Block A Section 1",
    accession: "10x Datasets (Space Ranger 1.x)",
    sourceUrl:
      "https://www.10xgenomics.com/datasets/human-breast-cancer-block-a-section-1-1-standard-1-1-0",
    modality: "10x Visium (fresh frozen)",
    role: "留出技术迁移样本：检查代码和映射能否在独立来源切片运行；缺少匹配病理/临床信息，不能验证命名边界 niche",
    sizeNote: "~3.8k spots；~300 MB",
    ramNote: "< 1 GB",
    priority: "validation",
  },
  {
    name: "LIANA 配体–受体资源（consensus）",
    accession: "liana-py 内置 (CellPhoneDB / CellChat / OmniPath)",
    sourceUrl: "https://liana-py.readthedocs.io/",
    modality: "先验知识库",
    role: "边界 niche 的配体–受体推断；结果标记为「推断」而非「机制」",
    sizeNote: "几 MB",
    ramNote: "忽略不计",
    priority: "knowledge",
  },
  {
    name: "Open Targets / Reactome / STRING / UniProt（经 BioNexus MCP）",
    accession: "REST APIs，无需密钥",
    sourceUrl: "https://github.com/HERRY423/BioNexus#-model-context-protocol-mcp-biological-layer",
    modality: "知识库",
    role: "对边界 DE 基因做通路/靶点 grounding；跨库矛盾由 BioNexus BN-F008 检测",
    sizeNote: "在线查询",
    ramNote: "忽略不计",
    priority: "knowledge",
  },
  {
    name: "Plan B：10x Visium 小鼠脑矢状切片 + Allen 皮层 scRNA 参考",
    accession: "squidpy / tangram 教程数据",
    sourceUrl: "https://squidpy.readthedocs.io/en/stable/notebooks/tutorials/tutorial_tangram.html",
    modality: "Visium + SMART-seq",
    role: "若乳腺癌数据不可恢复地受阻，用于技术演示；不得替代主要乳腺癌问题，也不称多患者或病理验证",
    sizeNote: "< 1 GB",
    ramNote: "< 4 GB",
    priority: "fallback",
  },
];

export const STAGES = [
  {
    code: "S0",
    title: "环境、模型分工与 Plan-first 立项",
    goal: "在 Workbench 中核实 NGS Analysis Workbench、Life Sciences Literature 与 BioNexus；由 Astra 冻结计划和主终点，经人工批准后再交给 Sol 执行。",
    plugin: "Rosalind Workbench + BioNexus preflight",
    tools: ["Codex", "conda/mamba", "scanpy", "squidpy", "tangram-sc", "pydeseq2", "liana", "bionexus"],
    memoryNote: "无内存压力。建议 Python 3.11 独立环境。",
    deliverable: "plan.md（Rosalind 生成并批准）+ bionexus preflight 报告 + environment.yml",
    screenshotHint: "Astra 提出计划并等待批准；BioNexus preflight 如实显示 6 sections，只有身份核实后才写 6 donors",
    estHours: 3,
    tasks: [
      { title: "Workbench → Plugins：核实 Life Sciences Literature 与 NGS Analysis Workbench", detail: "记录插件页面、版本和实际可调用能力；Astra/Sol 是模型，不计入插件清单。" },
      { title: "核实 BioNexus MCP", detail: "运行插件 doctor 并记录实际工具；不能用源代码存在代替当前 Workbench 会话可调用。" },
      { title: "创建 conda 环境", detail: "mamba create -n spatialwarrant python=3.11 scanpy squidpy tangram-sc pydeseq2 liana decoupler leidenalg -c conda-forge -c bioconda" },
      { title: "用 Astra 提交研究问题并锁定计划", detail: "保留 S0–S7 全方案；标出主分析、扩展分析、停止条件与每一步 provenance。" },
      { title: "bionexus preflight 评估计划", detail: "bionexus prevent \"boundary vs core pseudobulk DE across 6 sections\" —— 记录它给出的 design identifiability 与 claim ceiling。" },
    ],
  },
  {
    code: "S1",
    title: "公开数据获取与 Provenance 固化",
    goal: "拉取 GSE176078 与 Zenodo 4739739，哈希每个文件，写入 PROV-O sidecar，确保所有后续声明可追溯。",
    plugin: "Sol + Life Sciences Literature + BioNexus provenance-and-audit",
    tools: ["gpt-5.6-sol", "download client", "SHA-256", "BioNexus provenance", "Life Sciences Literature"],
    memoryNote: "预计磁盘占用需在下载清单后计算；保存真实大小、哈希、时间戳和失败日志。",
    deliverable: "data/manifest.json（SHA-256）+ provenance.prov.jsonld",
    screenshotHint: "MCP 调用 search_geo 返回 GSE176078 元数据；provenance sidecar 片段",
    estHours: 3,
    tasks: [
      { title: "查询 GSE176078，确认样本与文件清单", detail: "同时让 Life Sciences Literature 核对 Wu et al. 2021，并建立 patient–sample–section–subtype–lab 表。" },
      { title: "下载 GSE176078 原始计数矩阵与 metadata.csv", detail: "只需 Wu_etal_2021_BRCA_scRNASeq.tar.gz；解压后为 10x 格式 + metadata（含 celltype_major/minor/subset、Patient、subtype）。" },
      { title: "下载 Zenodo 4739739 的 6 张 Visium（filtered_count_matrices、spatial、metadata 病理标注）", detail: "注意保留 tissue_positions_list.csv 与 scalefactors_json.json。" },
      { title: "下载 10x 公开 Breast Cancer Block A Section 1 作为 held-out", detail: "filtered_feature_bc_matrix.h5 + spatial 文件夹。" },
      { title: "BioNexus provenance：对所有文件做 SHA-256 并生成 PROV-O", detail: "BioNexus 强调 hash-verified artifacts 才能计入证据；这一步决定后面 ledger 是否有效。" },
    ],
  },
  {
    code: "S2",
    title: "scRNA 参考构建（Rosalind NGS scRNA 工作流）",
    goal: "在 Rosalind Workbench 的单细胞流程中完成 QC、HVG、PCA、Leiden；BioNexus 只允许数字 cluster，并对作者标签做 annotation_evidence 打分。",
    plugin: "Rosalind NGS Analysis Workbench + BioNexus single-cell-rna-qc / scrna.annotation_evidence",
    tools: ["Rosalind scRNA workflow", "scanpy", "scrublet", "bionexus single-cell-rna-qc"],
    memoryNote: "峰值 ≈ 4 GB（全量加载后立刻分层下采样至 40k 细胞并落盘 h5ad）。",
    deliverable: "ref_40k.h5ad + EvidenceCard_ref.json + annotation_evidence.csv",
    screenshotHint: "Rosalind QC 报告；BioNexus EvidenceCard 显示「clusters numeric only; labels sourced from authors (external)」",
    estHours: 5,
    tasks: [
      { title: "检查并选择 scRNA 执行入口", detail: "先让 NGS Analysis Workbench 查询实时工作流目录；若无处理后矩阵入口，明确改用本地 Python，不能称注册工作流运行。" },
      { title: "分层下采样：每患者 × celltype_minor 上限，总量 ≤ 40k", detail: "保留稀有类型（如 Cycling T、pDC）最低 200 个；写成可复用 Skill。" },
      { title: "QC → 归一化 → HVG(2000, batch_key=Patient) → PCA → Harmony/BBKNN（可选）→ Leiden", detail: "BioNexus 规则：cluster 保持数字标签，不要让模型自己猜细胞类型。" },
      { title: "BioNexus scrna.annotation_evidence：以作者 celltype_minor 为外部标签，评估每个 cluster 的标签证据", detail: "输出每类的 marker 支持度、纯度、跨患者一致性；低分类型在后续去卷积中合并。" },
      { title: "生成参考 EvidenceCard（7 维）并存入 ledger", detail: "bionexus audit ref_40k.h5ad --purpose exploratory" },
    ],
  },
  {
    code: "S3",
    title: "Visium QC 与空间域 vs 发布者病理参考",
    goal: "逐切片 QC，Leiden 空间域；用 ARI/NMI 描述与发布者病理标注的一致性，并单独报告边界掩膜几何指标。",
    plugin: "BioNexus spatial-transcriptomics skill (squidpy)",
    tools: ["squidpy", "scanpy", "sklearn.metrics (ARI/NMI)", "bionexus spatial-transcriptomics"],
    memoryNote: "≈ 1–2 GB。",
    deliverable: "visium_qc/*.h5ad + domain_vs_pathology.csv + 6 张叠加图",
    screenshotHint: "6 张切片：左 H&E + 病理标注，右 Leiden 域；下方 ARI 表",
    estHours: 4,
    tasks: [
      { title: "读入 6 张切片（sc.read_visium），合并病理标注列", detail: "BioNexus 会检查坐标是否存在；缺坐标直接拒绝分析（这是它的硬规则，正好展示）。" },
      { title: "每切片 QC：UMI/基因数/线粒体比例；剔除组织外 spot", detail: "阈值按切片 MAD 自适应，不用固定魔数。" },
      { title: "Leiden 空间域（resolution 0.3–0.8 扫描）", detail: "把 resolution 扫描结果作为 BNS-007 参数敏感性证据。" },
      { title: "计算每张切片 ARI/NMI（Leiden 域 vs 病理标注）", detail: "不预期任何方向；同时报告 cluster 数与标签粒度差异，ARI/NMI 只作描述性辅助。" },
      { title: "记录 Claim C1 的证据事实并提交 BioNexus 审计", detail: "purpose=exploratory, claim_class=descriptive。" },
    ],
  },
  {
    code: "S4",
    title: "去卷积与跨方法一致性（BNS-007）",
    goal: "保留 Tangram cluster-mode；将 scanpy ingest 限定为标签迁移敏感性，不把它称为比例去卷积。加入 marker/NNLS 组成基线，分别报告三者可比的输出。",
    plugin: "BioNexus tangram 参考包 + spatial.inference_validity",
    tools: ["tangram-sc (mode='clusters')", "scanpy.tl.ingest", "decoupler (marker score, 第三方法可选)", "bionexus"],
    memoryNote: "Tangram cluster-mode 只映射 ~30 个 cluster 质心，≈ 2 GB；训练基因用 top 1000 marker。",
    deliverable: "proportions_tangram.csv / proportions_marker_nnls.csv / ingest_labels.csv / concordance.csv + 敏感性曲线",
    screenshotHint: "Tangram vs marker/NNLS 比例敏感性；ingest 标签图单列，阈值不预写",
    estHours: 6,
    tasks: [
      { title: "选择训练基因：每 celltype_minor top 50 marker（scanpy rank_genes_groups）并取交集", detail: "记录基因数；后面敏感性分析换 500/1000/2000。" },
      { title: "Tangram：tg.map_cells_to_space(mode='clusters', cluster_label='celltype_minor', device='cpu')", detail: "每切片 ~5–10 分钟；num_epochs 500 足够。" },
      { title: "第二组成基线：marker/NNLS", detail: "输出非负、和为 1 的组成估计；明确它是有限基线。sc.tl.ingest 只输出标签迁移，不称比例。" },
      { title: "一致性与敏感性：按输出类型比较", detail: "Tangram vs marker/NNLS 比较比例 Spearman；ingest 仅比较主导标签。共用参考使其成为方法敏感性，不是独立生物学证据。" },
      { title: "BioNexus spatial.inference_validity 审计去卷积结论", detail: "如果一致率 < 60% 它会把 ceiling 压到 FRAGILE——照实展示。" },
    ],
  },
  {
    code: "S5",
    title: "Niche 发现与肿瘤–免疫边界定义",
    goal: "先仅用病理区域和空间几何冻结边界；随后保留 spot 组成 niche 聚类、邻域富集、共现和 Moran's I，禁止组成结果反向修改主边界。",
    plugin: "BioNexus spatial-transcriptomics + spatial.inference_validity",
    tools: ["squidpy.gr.nhood_enrichment", "squidpy.gr.co_occurrence", "squidpy.gr.spatial_autocorr", "KMeans on proportions"],
    memoryNote: "≈ 1 GB。",
    deliverable: "niche_labels.csv + boundary_mask.csv + 6 张 niche 地图 + 富集热图",
    screenshotHint: "niche 地图叠加病理边界；nhood enrichment 热图中 CAF–T cell–Macrophage 边界模块",
    estHours: 5,
    tasks: [
      { title: "把 6 张切片的 spot 比例向量合并，KMeans(k=6~10) 得到跨切片 niche", detail: "用轮廓系数选 k，并把 k 扫描结果计入敏感性。" },
      { title: "冻结几何边界", detail: "boundary 只由 invasive cancer/stroma 病理区域与预注册距离阈值定义；core 为远离边界的 invasive cancer。免疫/基质比例不得参与。" },
      { title: "squidpy 邻域富集与共现：探索哪些细胞类型在边界共定位", detail: "CAF、CD8 T、Macrophage、endothelial 只是预指定关注对象；不保证出现。" },
      { title: "在 10x held-out 切片上复现 niche 分配（用训练好的 KMeans 中心）", detail: "held-out 没有病理标注，只做定性复现；BioNexus 会把该证据标为「无独立真值」。" },
      { title: "提交 Claim C3 审计（sample association 级）", detail: "证据事实：6 切片中几张出现该 niche；一致性数值。" },
    ],
  },
  {
    code: "S6",
    title: "边界生物学：配对 pseudobulk DE + 配体–受体 + 文献 grounding",
    goal: "核实独立单位后进行每样本 boundary vs core 配对 pseudobulk；保留 LIANA 推断与文献对照，并把预指定程序设为主终点、全基因 DE/L–R 设为扩展分析。",
    plugin: "Sol + local Python + BioNexus audit + Life Sciences Literature",
    tools: ["pydeseq2 (design ~ section + region)", "liana-py", "decoupler (PROGENy/Hallmark)", "BioNexus MCP search_reactome / search_string"],
    memoryNote: "≈ 1 GB。",
    deliverable: "de_boundary_vs_core.csv + lr_boundary.csv + literature_grounding.md + EvidenceCard_DE.json",
    screenshotHint: "六样本配对效应 + 火山图；EvidenceCard 显示实测设计、结果、限制和实际状态，不预写 SUPPORTED",
    estHours: 6,
    tasks: [
      { title: "构造 pseudobulk：每切片 × {boundary, core} 求和原始计数", detail: "目标为 12 个聚合样本；设计式 ~ section + region。仅在 section 对应独立患者经元数据核实后作患者级推断。" },
      { title: "pydeseq2 DE + BioNexus scrna.pseudobulk_de 审计", detail: "让 BioNexus 判定：cells≠replicates 已规避；配对可识别；人群外推被封顶。" },
      { title: "LIANA rank_aggregate：边界 niche 内部细胞类型间 L–R", detail: "结果标记为「推断」。重点看 CXCL9/10–CXCR3、CD274–PDCD1、TGFB1–TGFBR、SPP1–CD44。" },
      { title: "Life Sciences Literature：对 Top 20 DE 基因与 Top 10 L–R 做文献综合", detail: "要求输出「一致 / 矛盾 / 无报道」三栏与 PMID；再用 BioNexus external-evidence-audit 复核不双重计数。" },
      { title: "BioNexus MCP：search_reactome / search_string 给 DE 基因做通路 grounding", detail: "跨库矛盾（BN-F008）若被触发要保留截图。" },
    ],
  },
  {
    code: "S7",
    title: "证据审计、Evidence Debt 与提交物制作",
    goal: "跑 bionexus audit/verify/ledger/debt；故意投放一条过度解读陷阱；产出图版与推文。",
    plugin: "BioNexus ledger / debt / BioFailureBench + 本作战台",
    tools: ["bionexus verify", "bionexus ledger", "bionexus debt audit/payoff/graph", "Mermaid", "本 Next.js 作战台"],
    memoryNote: "无压力。",
    deliverable: "claim_ledger.jsonld + debt_graph.md + 8 张截图 + 推文串",
    screenshotHint: "Evidence Debt DAG；陷阱声明被 REFUSED；本作战台的 Claim Ledger 页面",
    estHours: 5,
    tasks: [
      { title: "bionexus verify：把 C1–C6 全部写入 Claim–Evidence Ledger 并导出 PROV-O JSON-LD", detail: "每条 claim 关联 supported_by 的数据 hash 与方法。" },
      { title: "bionexus debt audit / payoff / graph", detail: "预期 keystone：「去卷积跨方法一致性」——修复它能同时提升多条下游 claim。" },
      { title: "陷阱演示：要求 agent 用单张切片 1142243F 下「TNBC 人群级免疫排斥机制」结论", detail: "截图 BioNexus 的 PERMITTED_WITH_LIMITS/REFUSED 输出与 rule provenance（Squair 2021 等）。" },
      { title: "将真实 receipt 导入本作战台", detail: "页面只读展示机器状态；禁止用下拉框人工改写 verdict。人工科学裁决另存具名记录。" },
      { title: "制作 8 张截图 + 推文串，回复/引用 @ChrisHayduk", detail: "见「提交包」页面的清单与草稿。" },
    ],
  },
];

export const CLAIMS = [
  {
    code: "C1",
    statement: "检验 Visium Leiden 空间域与发布者病理区域的一致性，并报告每张切片 ARI/NMI、标签粒度和边界 Dice/Jaccard；不预设达到阈值。",
    claimClass: "descriptive",
    capability: "spatial.inference_validity",
    expectedCeiling: "TO_BE_COMPUTED",
    evidenceFacts: "尚未执行；producer-provided orthogonal reference，不是独立病理真值。",
    stageCode: "S3",
    isTrap: false,
  },
  {
    code: "C2",
    statement: "报告 Tangram 与 marker/NNLS 的 spot 组成敏感性，并单列 scanpy ingest 标签迁移一致性；不预设 70% 或相关阈值。",
    claimClass: "descriptive",
    capability: "spatial.inference_validity (BNS-007 cross-method)",
    expectedCeiling: "TO_BE_COMPUTED",
    evidenceFacts: "尚未执行；方法共用同一 scRNA 参考，只能构成方法敏感性，不能称独立生物学复现。",
    stageCode: "S4",
    isTrap: false,
  },
  {
    code: "C3",
    statement: "探索是否存在由 CAF、CD8 T、巨噬细胞与内皮共同表征的边界 niche，并报告其逐样本富集和稳定性。",
    claimClass: "association",
    capability: "spatial.inference_validity",
    expectedCeiling: "TO_BE_COMPUTED",
    evidenceFacts: "尚未执行；niche 不参与主边界定义；10x held-out 只作技术迁移，无匹配病理真值。",
    stageCode: "S5",
    isTrap: false,
  },
  {
    code: "C4",
    statement: "主终点：病理几何定义的边界 vs 核心配对 pseudobulk 中，预指定免疫/IFN 程序是否显示跨样本方向一致的差异；CXCL9/CXCL10/CXCL11/IDO1 为预指定关注基因。",
    claimClass: "population_effect",
    capability: "scrna.pseudobulk_de",
    expectedCeiling: "TO_BE_COMPUTED",
    evidenceFacts: "尚未执行；目标为 6 sections 配对，患者数、亚型和实验室混杂先核实；结论最多限定于该公开队列。",
    stageCode: "S6",
    isTrap: false,
  },
  {
    code: "C5",
    statement: "CXCL9/10–CXCR3 信号驱动 T 细胞向边界募集（机制/因果）。",
    claimClass: "causal",
    capability: "scrna.pseudobulk_de + external-evidence-audit",
    expectedCeiling: "ABSTAIN",
    evidenceFacts: "仅相关性与 L–R 推断，无扰动数据；文献支持但本数据不能独立证明。只能作为假设。",
    stageCode: "S6",
    isTrap: false,
  },
  {
    code: "C6",
    statement: "边界 niche 签名可预测乳腺癌患者对免疫治疗的响应。",
    claimClass: "clinical",
    capability: "Invariant (INVARIANT_SAFETY)",
    expectedCeiling: "REFUSED",
    evidenceFacts: "无治疗队列、无外部验证、RUO；任何 lab policy 下均 ESCALATE/BLOCK。",
    stageCode: "S7",
    isTrap: false,
  },
  {
    code: "T1",
    statement: "【陷阱】仅凭切片 1142243F（n=1）得出「TNBC 人群普遍存在免疫排斥边界」的结论。",
    claimClass: "population_effect",
    capability: "scrna.pseudobulk_de (BN-F002 cells≠replicates)",
    expectedCeiling: "ABSTAIN",
    evidenceFacts: "n=1 section；用于验证审计是否拒绝人群外推，保留 BioNexus 实际返回，不预写状态。",
    stageCode: "S7",
    isTrap: true,
  },
  {
    code: "T2",
    statement: "【技术阳性对照】输入清单中的文件哈希、barcode 对齐与空间坐标完整性可被重复验证。",
    claimClass: "descriptive",
    capability: "spatial.inference_validity",
    expectedCeiling: "TO_BE_COMPUTED",
    evidenceFacts: "不使用分析结果定义阳性对照；仅检验可重复的技术完整性，不能提升生物学声明。",
    stageCode: "S7",
    isTrap: true,
  },
];

export const TIMELINE = [
  { day: "Day 1", focus: "S0 + S1：环境、插件、数据下载、provenance", hours: 6 },
  { day: "Day 2", focus: "S2 + S3：scRNA 参考、Visium QC、域 vs 病理", hours: 8 },
  { day: "Day 3", focus: "S4：Tangram + ingest 去卷积、一致性、敏感性", hours: 7 },
  { day: "Day 4", focus: "S5 + S6：niche、边界、pseudobulk DE、L–R、文献", hours: 8 },
  { day: "Day 5", focus: "S7：审计、debt DAG、陷阱演示、截图、推文", hours: 5 },
];

export const SCREENSHOTS = [
  "Astra 在 Workbench 中冻结主问题、统计单位、停止条件并等待你的批准",
  "NGS Analysis Workbench 返回实时目录能力：若无 processed matrix 工作流，明确转为本地 Python",
  "Life Sciences Literature 的真实返回：Wu 2021 样本设计、PMID/DOI 与成功/失败记录",
  "6 张切片：H&E + 发布者病理区域 + 纯几何 boundary/core 掩膜",
  "Tangram vs marker/NNLS 组成敏感性；scanpy ingest 标签迁移独立成图",
  "六个独立样本配对效应 + 火山图；显示方向、区间、FDR 与 leave-one-sample-out",
  "只读 BioNexus EvidenceCard / Evidence Debt DAG：哈希、实际状态、限制和未满足证据",
  "越界声明被审计拒绝 + 具名 Human Scientific Adjudication；UI 无人工改 verdict 控件",
];

export const TWEET_THREAD = [
  `DRAFT — fill brackets only after the verified run. @ChrisHayduk I built SpatialWarrant in Rosalind Workbench: an evidence-audited analysis of the breast-tumor boundary across six public Visium sections. [ONE SENTENCE WITH THE OBSERVED RESULT.] 🧵`,
  `Rosalind plugins actually used: NGS Analysis Workbench for data/design checks; Life Sciences Literature for source-grounded interpretation; BioNexus Reliability for hashes, provenance and claim limits. Local Python/scverse performed the custom spatial statistics.`,
  `The boundary was frozen from producer-provided pathology geometry before expression testing. Spots were aggregated within section, and the verified biological samples—not thousands of spots—were the inferential units. [ADD EFFECT, INTERVAL AND DIRECTIONAL CONSISTENCY.]`,
  `I also tested an overclaim: could one section support a population-level TNBC immune-exclusion mechanism? BioNexus kept the actual fail-closed verdict and recorded the missing replication and causal evidence. [ADD EXACT RETURN.]`,
  `The full design stays in the project: spatial domains, Tangram, marker/NNLS sensitivity, niche analysis, LIANA and a 10x transfer check. Same-study pathology and scRNA are labeled as reference evidence, not independent validation.`,
  `Reproducibility: [INPUT MANIFEST SHA-256], [CODE REVISION], [ACTUAL PEAK RAM/RUNTIME]. Astra challenged the design and final claims; Sol executed and preserved the files. Screenshots show the real Workbench/plugin calls and results.`,
];
